config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  

  root 'home#index'

  get '/about' => 'home#about', as: :about
  get '/privacy' => 'home#privacy', as: :privacy
  get '/tos' => 'home#tos', as: :tos
  get '/:profession_id/u' => 'users#pindex', as: :profession_users
  get '/:user_id/projects/:id' => 'projects#show', as: :user_project

  resources :projects, only: [:create, :edit, :new, :update, :destroy]

  resources :users, only: [:index, :show] , path: 'u' do
    member do
      get 'dashboard'
      get 'likes'
      get 'posts'
      get 'hireme'
      post 'hireme'
      get 'drafts'
      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :tags, only: [:show], path: 'tag' do
  end

  
  resources :posts, only: [:create, :edit, :update, :destroy, :new, :index] do
    collection do
      post :autosave
      get 'search'
      get 'explore'
      get 'topics'
      get 'feed'
      get 'top'
    end
    
    member do
      post 'publish'
      post 'like'
      post 'rcount' => 'posts#increment_read_count'
    end
  end
  resources :topics, only: [:show, :update, :new, :edit, :create], path: 't'
  get '/search' => 'posts#search', as: 'search'
  get ':user_id/:id' => 'posts#show', as: 'seo_post'

  resources :likes, only: [:index, :update, :destroy, :create]

  resources :post_assets, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  # store_accessor :extras, :technologies, :other_professions

  after_commit :welcome_message, on: :create

  attr_accessor :login
  has_many :posts
  has_many :post_assets
  has_many :likes

  has_many :subscriptions, :foreign_key => 'subscribed_to_id'
  has_many :subscribers, through: :subscriptions

  has_many :user_subscribed, :foreign_key => 'subscriber_id', class_name: 'Subscription'
  has_many :subscribed_tos, through: :user_subscribed, :source => :subscribed_to

  acts_as_follower

  has_many :hiring_emails, :foreign_key => 'sender_id'

  belongs_to :profession
  # before_save :fix_short_profile

  has_many :projects, dependent: :destroy
  validate :profession_present

  extend FriendlyId
  friendly_id :username, use: :slugged

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, length: {maximum: 255}, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }
  validates_uniqueness_of :username, case_sensitive: false, message: 'allready taken'
  validates :one_liner, presence: true

  accepts_nested_attributes_for :projects, allow_destroy: true
  include PgSearch
  pg_search_scope :search,
                  :against => {
                    :name => 'A',
                    :technologies => 'B',
                    :company_name => 'B',
                    :one_liner => 'C',
                    :website => 'B',
                    :bio => 'D'
                    },
                  :using => {
                    :tsearch => {:prefix => true, :dictionary => "english", :tsvector_column => 'search_term'}
                  }

  include Countable
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def seo_title
    "#{self.name} profile"
  end

  def seo_description
    self.one_liner.present? ? self.one_liner : "Profile created by #{self.name} on"
  end

  def seo_keywords
    []
  end

  def subscribed_already?(user)
    Subscription.where(subscriber_id: self.id, subscribed_to_id: user.id).pluck(:id)[0]
  end

  def subscribe_to(user)
    Subscription.create(subscriber_id: self.id, subscribed_to_id: user.id) unless self.subscribed_already?(user) 
  end

  def unsubscribe_from(user)
    Subscription.where(subscriber_id: self.id, subscribed_to_id: user.id).delete_all
  end

  def like?(post)
    Like.where(post_id: post.id, user_id: self.id).pluck(&:id)[0]
  end

  def formatted_profession
    (profession && profession.name == 'Other') ? profession_name : profession.name
  end

  def like(post)
    Like.create(post_id: post.id, user_id: self.id)
    post.increment_count(:likes_count)
  end
private

  def welcome_message
    UserMailer.welcome(self).deliver_later
  end

  # def fix_short_profile
  #   if self.name.present? && self.bio.present?
  #     self.short_profile = false
  #   else
  #     self.short_profile = true
  #   end
  #   true
  # end

  def profession_present
    self.errors[:base] << "Designation name can't be blank" if self.profession && self.profession.try(:name) == 'Other' && !self.profession_name.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:show, :posts, :drafts, :likes, :subscribe, :unsubscribe, :hireme]
  before_action :authenticate_user!, only: [:drafts, :subscribe, :unsubscribe, :hireme]

  def index
    unless params[:q]
      @users = User.page(params[:page]).includes(:profession).order("created_at desc")
    else
      @users = User.search(params[:q]).page(params[:page]).includes(:profession)
    end
  end

  def pindex
    @profession = Profession.friendly.find(params[:profession_id])
    unless params[:q]
      @users = User.where(profession_id: @profession.id).page(params[:page]).includes(:profession).order("created_at desc")
    else
      @users = User.where(profession_id: @profession.id).search(params[:q]).page(params[:page]).includes(:profession)
    end
  end

  def hireme
    if request.post?
      @hiring_email = HiringEmail.new(hiring_email_params)
      @hiring_email.sender_id = current_user.id
      @hiring_email.receiver_id = @user.id
      if @hiring_email.save
        redirect_to user_path(@user), notice: "Message successfully sent to #{@user.name}"
      else
        render 'hireme'
      end
    else
      @hiring_email = HiringEmail.new(email: current_user.email)
      render 'hireme'
    end
  end

  def show
    @top_posts = @user.posts.published.limit(5).order('likes_count desc')
    @projects = @user.projects
  end

  def dashboard
  end

  def likes
    @likes = @user.likes.page(params[:page]).order("created_at desc").includes(:post)
  end

  def subscribe
    current_user.subscribe_to(@user)
    render json: {}
  end

  def unsubscribe
    current_user.unsubscribe_from(@user)
    render json: {}
  end

  def posts
    @posts = @user.posts.published.page(params[:page]).order("created_at desc")
  end

  def drafts
    @posts = @user.posts.not_published.page(params[:page]).order("created_at desc")
  end

private 

  def hiring_email_params
    params.require(:hiring_email).permit(:content, :email)
  end
  
  def find_user
    @user = User.friendly.find(params[:id])
    not_found unless @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form_fields.html.erb
<div class='form-group'>
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: 'Name' %>
</div>

<div class='form-group'>
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
</div>

<div class='form-group'>
  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control', placeholder: 'username' %>
</div>

<div class='form-group'>
  <%= f.label :one_liner, 'One liner about you' %>
  <%= f.text_field :one_liner, class: 'form-control', placeholder: 'One liner about you' %>
</div>

<div class='form-group'>
  <%= f.label :profession_id, 'Designation' %>
  <%= f.select :profession_id, Profession.all.order('name').map{|p| [p.name, p.id]}, {}, {class: 'form-control'} %>
</div>

<div class='form-group <%= 'hide' unless @user.profession.try(:name) == 'Other' %>'>
<%= f.text_field :profession_name, class: 'form-control' %>
</div>

<div class='form-group'>
  <%= f.label :is_available do  %>
    <%= f.check_box :is_available  %> Available for work
  <% end %>
</div>

<div class='form-group'>
  <%= f.label :is_availablity_public do  %>
    <%= f.check_box :is_availablity_public  %> Make Availablilty Status Public
  <% end %>
  <small class='help-block m-0 bold'>Note: Checking the box above enables other members to contact you. A member can send you two messages maximum. We will not share your email.</small>
</div>

<div class='form-group'>
  <%= f.label :technologies, 'Technologies you work on'  %>
  <%= f.text_field :technologies, value: f.object.technologies.join(", "), class: 'form-control'   %>
</div>


<div class='form-group'>
  <%= f.label :profession_id, 'Company Name' %>
  <%= f.text_field :company_name, class: 'form-control', placeholder: 'Company Name' %>
</div>

<div class='form-group'>
  <% if @user.avatar? %>
    <p class='text-center'>
    <%= image_tag(@user.avatar.medium.url, class: 'img-thumbnail profile-img img-circle')  %>
    </p>
  <% end %>
  <%= f.label :avatar %>
  <%= f.file_field :avatar, class: 'btn btn-success' %>
  <%= f.hidden_field :avatar_cache %>
</div>

<div class='form-group'>
  <%= f.label :website %>
  <%= f.text_field :website, class: 'form-control', placeholder: 'Website (http://website.com)' %>
</div>
<div class='form-group'>
  <%= f.label :twitter %>
  <%= f.text_field :twitter, class: 'form-control', placeholder: 'Twitter (https://twitter.com/username)' %>
</div>
<div class='form-group'>
  <%= f.label :linked_in, "Linkedin" %>
  <%= f.text_field :linked_in, class: 'form-control' , placeholder: 'Linkedin (http://in.linkedin.com/in/vipinnagpal)' %>
</div>
<div class='form-group'>
  <%= f.label :github %>
  <%= f.text_field :github, class: 'form-control', placeholder: 'Github (https://github.com/user)'  %>
</div>

<div class='form-group'>
  <i class='help-block'>Tell us about you. Be creative, our readers are curious.</i>
  <%= f.text_area :bio, class: 'form-control', rows: '6', placeholder: 'Tell us something about yourself' %>
</div>

<div class='form-group'>
<%= f.label :password %>
<%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder: 'Password' %>
<i class: 'help-block'>(leave blank if you don't want to change it)</i>
</div>

<div class='form-group'>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder: 'Confirm Password' %>
</div>

app/views/users/_profession.html.erb
<ul class='text-muted m-0 list-inline'>
  <% if user.profession %>
    <li>
      <%= user.formatted_profession %>
      <% if user.company_name %>
        at <%= user.company_name %>
      <% end %>
    </li>
  <% end %>
  <% if user.technologies.present? %>
    <li>
      —
    </li>
    <li>
      <%= user.technologies.compact.map{|tech| link_to tech, users_path(q: tech)}.join(', ').html_safe %>
    </li>
  <% end %>
</ul>

app/views/users/_profile.html.erb
<div class='text-center' id='user-profile'>
  <%= link_to user_path(@user) do %><%= image_tag(user.avatar.medium.url, class: 'img-thumbnail profile-img img-circle')  %><% end %>
  <h2></span><%= user.name %> <small>(@<%= user.username %>)</small></h2>

    <div>
      
      <h3 class='text-muted m-0'>
        <% if user.profession %>
          <%= user.formatted_profession %>
          <% if user.company_name %>
            at <%= user.company_name %>
          <% end %>
        <% end %>
      </h3>

      <ul class='m-0 list-inline' id='social'>
        <% if user.website.present? %>
          <li>
            <%= link_to "<span class='entypo-globe'></span>".html_safe, user.website, target: '_blank' %>
          </li>
        <% end %>
        <% if user.twitter.present? %>
          <li>
            <%= link_to "<span class='entypo-twitter'></span>".html_safe, user.twitter, target: '_blank' %>
          </li>
        <% end %>
        
        <% if user.github.present? %>
          <li>
            <%= link_to "<span class='entypo-github'></span>".html_safe, user.github, target: '_blank' %>
          </li>
        <% end %>

        <% if user.linked_in.present? %>
          <li>
            <%= link_to "<span class='entypo-linkedin'></span>".html_safe, user.linked_in, target: '_blank' %>
          </li>
        <% end %>
        
      </ul>

      <% if user.technologies.present? %>
        <h3 class='m-0'>
          Technologies: <%= user.technologies.compact.map{|tech| link_to tech, users_path(q: tech)}.join(', ').html_safe %>
        </h3>
      <% end %>
      
    </div>
 




  
</div>
<h2 class='text-muted m-0 text-center'>

  <%= user.one_liner %>

</h2>
<div class="nav text-center m-t-15">

    <%= link_to 'Posts', posts_user_path(@user) %>


    <%= link_to 'Likes', likes_user_path(@user) %>

    <% if current_user == @user %>
      <%= link_to 'Edit Account', edit_user_registration_path %>
      <%= link_to 'Add a Project', new_project_path %>
    <% else %>
      <% if @user.is_availablity_public %>
        <% unless user_signed_in? %>
          <%= link_to 'Hire ME', new_user_session_path(alert: 'hireme') %>
        <% else %>
          <%= link_to 'Hire ME', hireme_user_path(@user) %>
        <% end %>
      <% end %>
    <% end %>

</div>
<hr class='m-t-b-30'>

app/views/users/_projects.html.erb
<% if projects.present? %>
<div class="row">
  <div class="col-xs-12 m-b-30">
    <h2 class='m-0'><%= @user.name %>'s Projects</h2>
  </div>
  <div class="row">
    
    <% projects.each do |pro| %>
      <div class='col-xs-12 col-sm-4 col-md-3 text-center'>
        <%= link_to user_project_path(user_id: @user.slug, id: pro.slug) do %>
          <%= image_tag pro.image.medium.url, alt: pro.name, class:  'img-thumbnail' %>
        <% end %>
        <h2 class='f-lg'>
          <%= pro.name %>
        </h2>
        <p class='f-sm no-bold f-sans'>
          <%= pro.short_description %>
          <% if current_user == @user %>
            <%= link_to 'Edit Project', edit_project_path(pro)  %>
          <% else %>
            <%= link_to 'View more', user_project_path(user_id: @user.slug, id: pro.slug) %> 
          <% end %>
        </p>
      </div>
    <% end %>

  </div>

</div>
<% end %>

app/views/users/_search_form.html.erb
<div class='row m-t-30'>
  <div class='col-xs-12 col-sm-6'>
    <div class="dropdown">
      
      <div id='profession-s-text'>Show Me <a data-toggle="dropdown" href="#"><%= @profession.try(:name) || 'Anybody' %> <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
          <li><%= link_to 'Anybody', users_path %></li>
          <% Profession.all.map do |p| %>
            <li><%= link_to p.name.pluralize, profession_users_path(profession_id: p.slug) %></li>
          <% end %>
        </ul>
      </div>
      
    </div>
  </div>
  <div class='col-xs-12 col-sm-6'>
    <%= form_tag request.path_info, method: :get, id: 'search-form', role: 'form' do |f| %>
      <div class='form-group'>
        <div class="input-group">
          <div class="input-group-addon"><span class='entypo-search'></span></div>
          <%= text_field_tag :q, params[:q], class: 'form-control default-input', placeholder: 'Search by some text' %>
        </div>
        <%= link_to 'search', "#{request.path_info}?",id: 'search-link-mask', style: 'display: none' %>
        <%= submit_tag '.', class: 'search-btn hide' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="post">
  <section>
    <div class="post-preview col-xs-10  no-gutter">

      <h2>
        <%= link_to user.name, user_path(user) %><small> (@<%= user.username %>)</small>
        
      </h2>
      <%= render partial: 'profession', locals: {user: user} %>
     
      
    </div>

    <div class=" col-xs-2 no-gutter">
  
      <%= image_tag user.avatar.thumb, class: 'user-icon user-1', alt: user.name %>
 
    </div>

  </section>
</div>

app/views/users/drafts.html.erb
<%
  title t('.meta_title')
  description t('.meta_description')
  
%>

<div class="home-page-posts animated fadeIn">
  <h1 class='text-center'>My Drafts</h1>
  <hr>
  
  <%= render @posts %>  
  <%= paginate @posts %>
</div><!-- Home page posts -->

app/views/users/hireme.html.erb
<%
  title "Hire #{@user.name}"
  
%>
<h2 class='text-center'><%= "Hire #{@user.name}" %></h2>
<hr>
<%= form_for(@hiring_email, url: hireme_user_path(@user)) do |f| %>
  <% if @hiring_email.errors.any? %>
    <ul class='alert alert-warning list-unstyled'>
      <h2><%= pluralize(@hiring_email.errors.count, "error") %> prohibited this post from being saved</h2>
      <% @hiring_email.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class='form-group'>
    <%= f.label :email, "Sender Email(Your email address will be shrared with #{@user.name})" %>
    <%= f.text_field :email,  class: 'form-control', placeholder: 'Sender Email' %>
  </div>

  <div class='form-group'>
    <%= f.label :content, "Type you message below." %>
    <%= f.text_area :content,  class: 'form-control', placeholder: 'Type youe message' %>
  </div>

  

  <div class='clearfix'>
    <%= f.submit "Send Message", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/users/index.html.erb
<%
  title t('.meta_title')
  description t('.meta_description')
  keywords ['startup', 'funding', 'developers', 'designer']
  canonical users_url
%>
<%= render partial: 'posts/pmenu' %>

<div class="home-page-posts animated fadeIn">
  
  <h1 class='text-center'>Recent people joined the community</h1>
  <%= render "search_form" %>
  <hr class='m-t-b-30'>

  <%= render @users %>
  <%= paginate @users%>
</div>

app/views/users/likes.html.erb
<%
  title t('.meta_title', user: @user.name)
  description t('.meta_description', user: @user.name)
  canonical likes_user_url(@user)
%>


<div class="favorite-posts clearfix animated fadeIn ">
  <h1 class='text-center'><%= @user.name %>'s Likes</h1>
  <hr>
    <section>
      <% @likes.each do |like| %>
        <% post = like.post %>
        <div class="post-favorite col-xs-12 col-sm-6  no-gutter">
          <h2><%= link_to post.title, seo_post_path(post.user, post) %></h2>
          <p><%= post.subtitle %></p>
        </div>
      <% end %>
    </section>
</div>

app/views/users/pindex.html.erb
<% 
  pprof = @profession.name.pluralize
  title t('.meta_title', profession: pprof)
  description t('.meta_description', profession: pprof)
  canonical users_url
%>
<%= render partial: 'posts/pmenu' %>

<div class="home-page-posts animated fadeIn">
  <h1 class='text-center'>Recent <%= @profession.name %> joined the community</h1>
  <%= render "search_form" %>
  <hr>
  <%= render @users %>
  <%= paginate @users %>
</div>

app/views/users/posts.html.erb
<%
  title t('.meta_title', user: @user.name)
  description t('.meta_description', user: @user.name)
  canonical posts_user_url(@user)
%>
<div class="home-page-posts animated fadeIn">
  <h1 class='text-center'><%= @user.name %>'s Posts</h1>
  <hr>
  
  <%= render @posts %>  
  <%= paginate @posts %>
</div><!-- Home page posts -->

app/views/users/show.html.erb
<%
  title t('.meta_title', title: @user.seo_title)
  description t('.meta_description', description: @user.seo_description)
  keywords @user.seo_keywords
  canonical user_path(@user)
%>



<%= render partial: 'profile', locals: {user: @user} %>
<% if @user.bio.present? %>
  <div class='small'>
    <%= @user.bio.html_safe %>
  </div>
<% end %>
<hr/>
<%= render partial: 'projects', locals: {projects: @projects} %>
<%= render partial: 'posts/top_posts', locals: {top_posts: @top_posts} %>