config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  

  root 'home#index'

  get '/about' => 'home#about', as: :about
  get '/privacy' => 'home#privacy', as: :privacy
  get '/tos' => 'home#tos', as: :tos
  get '/:profession_id/u' => 'users#pindex', as: :profession_users
  get '/:user_id/projects/:id' => 'projects#show', as: :user_project

  resources :projects, only: [:create, :edit, :new, :update, :destroy]

  resources :users, only: [:index, :show] , path: 'u' do
    member do
      get 'dashboard'
      get 'likes'
      get 'posts'
      get 'hireme'
      post 'hireme'
      get 'drafts'
      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :tags, only: [:show], path: 'tag' do
  end

  
  resources :posts, only: [:create, :edit, :update, :destroy, :new, :index] do
    collection do
      post :autosave
      get 'search'
      get 'explore'
      get 'topics'
      get 'feed'
      get 'top'
    end
    
    member do
      post 'publish'
      post 'like'
      post 'rcount' => 'posts#increment_read_count'
    end
  end
  resources :topics, only: [:show, :update, :new, :edit, :create], path: 't'
  get '/search' => 'posts#search', as: 'search'
  get ':user_id/:id' => 'posts#show', as: 'seo_post'

  resources :likes, only: [:index, :update, :destroy, :create]

  resources :post_assets, only: [:create, :destroy]

end

app/views/shared/_bar.html.erb
<span class="menu-trigger writer-icon animated fadeInDown">
  <span class="bar"></span>
  <span class="bar"></span>
  <span class="bar"></span>
</span>

app/views/shared/_big_search.html.erb
<div class='text-center' id='explore-container'>
  <h1>Find something to read</h1>
  <hr>
  <%= form_tag search_path, method: :get, id: 'search-form', role: 'form' do |f| %>
    <div class='form-group'>
      <div class="input-group">
        <div class="input-group-addon"><span class='entypo-search'></span></div>
        <%= text_field_tag :q, params[:q], class: 'form-control default-input input-lg', placeholder: 'Search by some text' %>
      </div>
      <%= link_to 'search', '/search?',id: 'search-link-mask', style: 'display: none' %>
      <%= submit_tag '.', class: 'search-btn hide' %>
    </div>
  <% end %>
</div>

app/views/shared/_discuss.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'weareindiatech';
    var disqus_identifier = '<%= post.id %>';
    var disqus_url = '<%= seo_post_url(post.user, post) %>';
    
    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/shared/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/favicon_android/manifest.json">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_flash.html.erb
<div id='flash-bar'>
  <% flash.each do |name, msg| %>
    <div class='alert <%= "alert-#{(name.to_s == "notice" || name.to_s == "success") ? 'success' : 'danger'}" %>'>
      <a class="close" data-dismiss="alert">&#215</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
</div>

app/views/shared/_home_splash.html.erb
<div class="hero-image hero-a-great-story">
  <!-- if the user has javascript disabled they can still use the menu -->
  <noscript>
    <div class="no-js-menu">
      <%= render 'shared/menu_items' %>
    </div>
  </noscript>
  <!-- end no script -->

  <div class="site-info">
    <div class="primary-info">
      <h1>We Are India Tech</h1>
      <p>We features the faces and profiles of our indian tech community. </p>
    </div>
    <% unless user_signed_in? %>
      <div class="secondary-info">
        <p>
        <%= link_to '<i class="entypo-doc-text"></i>Join'.html_safe,  new_user_registration_path, class: 'btn btn-writer btn-post' %> &nbsp; to &nbsp; 
        <%= link_to 'Share your story', new_user_registration_path %></p>
      </div>
    <% else %>
      <div class="secondary-info">
        <p><%= link_to 'Share your story', new_post_path %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_menu_items.html.erb
<% if user_signed_in? %>
  <ul>
    <li><i class="entypo-star"></i>
      <%= link_to 'Explore', posts_path %>
    </li>
    <li><i class="entypo-home"></i>
      <%= link_to 'Home',root_path %>
    </li>
    <li><i class="entypo-user"></i>
      <%= link_to current_user.name ,user_path(current_user) %>
    </li>
    <li><i class="entypo-docs"></i>
      <%= link_to 'My Posts' , posts_user_path(current_user) %>
    </li>
    <li><i class="entypo-brush"></i>
      <%= link_to 'Add New Post' , new_post_path %>
    </li>
    <li><i class="entypo-newspaper"></i>
      <%= link_to 'Drafts' , drafts_user_path(current_user) %>
    </li>    
    <li><i class="entypo-logout"></i>
      <%= link_to 'Sign out', destroy_session_path(current_user), method: 'delete' %>
    </li>
  </ul>
<% else %>

  <ul>
    <li><i class="entypo-star"></i>
      <%= link_to 'Explore', posts_path %>
    </li>
    <li><i class="entypo-home"></i>
      <%= link_to 'Home', root_path %>
    </li>
    <li><i class="entypo-user"></i>
      <%= link_to 'Sign in', new_user_session_path %>
    </li>
    <li><i class="entypo-user-add"></i>
      <%= link_to 'Join', new_user_registration_path %>
    </li>

  </ul>
<% end %>

app/views/shared/_noscript_menu.html.erb
<div class="" style="">
  <!-- if the user has javascript disabled they can still use the menu -->
  <noscript>
    <div class="no-js-menu">
      <%= render 'shared/menu_items' %>
    </div>
  </noscript>
  <!-- end no script -->
</div>

app/views/shared/_sidebar.html.erb
<div id="menu">
  <%= render 'shared/menu_items' %>
</div>
<div class="sidebar col-md-5 col-sm-12 ">

  <%= render 'shared/bar' %>

    <!-- if the user has javascript disabled they can still use the menu -->
  <%= render 'shared/noscript_menu' %>
  <!-- end no script -->

  <div class="site-info">
    <div class="primary-info">
      <h1>We Are India Tech</h1>
      <p>We features the faces and profiles of our indian tech community. </p>
    </div>
    <% unless user_signed_in? %>
      <div class="secondary-info">
        <p>
        <%= link_to '<i class="entypo-doc-text"></i>Join'.html_safe,  new_user_registration_path, class: 'btn btn-writer btn-post' %>&nbsp; to &nbsp;
        <%= link_to 'Share your story', new_user_registration_path %></p>
      </div>
    <% else %>
      <div class="secondary-info">
        <p><%= link_to 'Share your story', new_post_path %></p>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_sidebar_topic.html.erb
<div id='menu'>
  <%= render 'shared/menu_items' %>
</div>
<div class="sidebar category-sidebar col-md-5 col-sm-12" style="background-image: url('<%= @topic.splash.main.url %>')">

  <%= render 'shared/bar' %>

  <!-- if the user has javascript disabled they can still use the menu -->

  <%= render 'shared/noscript_menu' %>

  <!-- end no script -->

  <div class="site-info">
    <div class="primary-info alpha clearfix topic-blk">
      <%= follow_or_unfollow(@topic, 'pull-right', @following_ids) %>
      <h1><%= @topic.title %></h1>
      <p><%= @topic.description %></p>
    </div>
    <div class="secondary-info">

    </div>
  </div>

</div>