config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  

  root 'home#index'

  get '/about' => 'home#about', as: :about
  get '/privacy' => 'home#privacy', as: :privacy
  get '/tos' => 'home#tos', as: :tos
  get '/:profession_id/u' => 'users#pindex', as: :profession_users
  get '/:user_id/projects/:id' => 'projects#show', as: :user_project

  resources :projects, only: [:create, :edit, :new, :update, :destroy]

  resources :users, only: [:index, :show] , path: 'u' do
    member do
      get 'dashboard'
      get 'likes'
      get 'posts'
      get 'hireme'
      post 'hireme'
      get 'drafts'
      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :tags, only: [:show], path: 'tag' do
  end

  
  resources :posts, only: [:create, :edit, :update, :destroy, :new, :index] do
    collection do
      post :autosave
      get 'search'
      get 'explore'
      get 'topics'
      get 'feed'
      get 'top'
    end
    
    member do
      post 'publish'
      post 'like'
      post 'rcount' => 'posts#increment_read_count'
    end
  end
  resources :topics, only: [:show, :update, :new, :edit, :create], path: 't'
  get '/search' => 'posts#search', as: 'search'
  get ':user_id/:id' => 'posts#show', as: 'seo_post'

  resources :likes, only: [:index, :update, :destroy, :create]

  resources :post_assets, only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  include PgSearch
  has_many :post_assets

  has_many :post_topics, dependent: :destroy
  has_many :topics, through: :post_topics

  default_scope {select([:id, :content, :title, :user_id, :created_at, :updated_at, :subtitle, :published, :slug, :duration,:likes_count, :read_count, :tags, :published_at])}
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :likes

  validates :topic_ids, :title, :content, :user_id, presence: true
  before_save :set_duration
  after_save :set_published_at
  scope :published, -> { where(published: true) }
  scope :not_published, -> { where(published: false) }
  include Countable

    pg_search_scope :post_search,
                  :against => {
                    :title => 'A', 
                    :subtitle => 'B', 
                    :content => 'C'
                    },
                  :using => {
                    :tsearch => {:prefix => true, :dictionary => "english", :tsvector_column => 'search_term'}
                  }

    def short_url
      "#{ENV['WEBSITE']}/#{self.id}"
    end

    def primary_asset_url
      ps = self.post_assets.first
      ENV['WEBSITE'] + ps.passet.url if ps
    end

    def seo_title
      self.title.truncate(35)
    end

    def seo_tags
      self.tags + self.topics.map(&:title)
    end

    def seo_description
      self.subtitle.present? ? self.subtitle.truncate(100) : Rails::Html::FullSanitizer.new.sanitize(self.content).truncate(200)
    end
private
  def set_duration
    if self.new_record? || self.content_changed?
      words_count = Rails::Html::FullSanitizer.new.sanitize(self.content).scan(/\w+/).size
      self.duration = (words_count/200.0).ceil
    end
  end

  def set_published_at
    if self.published && !self.published_at
      self.touch(:published_at)
      user = self.user
      post = self
      user.subscribers.each do |sub|
        UserMailer.subscription_email(sub, post, user).deliver_later
      end
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :like, :increment_read_count]
  before_action :set_user_post, only: [:edit, :update, :destroy, :publish]
  before_action :authenticate_user!, only: [:create, :edit, :new, :update, :destroy, :autosave, :feed, :publish, :like]
  before_action :full_profile_user, only: [:new]
  before_action :get_topics, only: [:new, :edit, :topics]
  before_action :parse_tags, only: [:create, :update]

  def index
    @posts = Post.published.page(params[:page]).order('created_at desc').includes(:topics, :user)
    respond_to do |format|
      format.html {}
      format.json {render json: @posts}
    end
  end

  def increment_read_count
    @post.increment_count(:read_count)
    render json: {}
  end

  def top
    @posts = Post.published.page(params[:page]).order('likes_count').includes(:topics, :user)
    respond_to do |format|
      format.html { render 'index'}
      format.json {render json: @posts}
    end
  end

  def feed
    @posts = Post.published.distinct.joins(:post_topics).where("post_topics.topic_id in (?)", current_user.follows.pluck("followable_id") ).page(params[:page]).order("created_at desc").includes(:topics, :user)
  end

  def publish
    @post.update_attributes(published: true)
    render json: {}
  end

  def topics
    @following_ids = current_user ? current_user.follows.pluck("followable_id") : []
  end

  def explore
    if current_user
      Post.published.joins(:post_topics).where("post_topics.topic_id in (?)", current_user.follows.pluck("followable_id") )
    else
      Post.published
    end
  end

  def show
    @likes = @post.likes.includes(:user).limit(10).order("created_at desc")
    @user = @post.user
    respond_to do |format|
      format.html {}
      format.json {render json: @post}
    end
  end

  def like
    current_user.like(@post)
    render json: {}
  end

  def autosave
    
  end

  def search
    @posts = Post.published.post_search(params[:q]).includes(:topics, :user).page(params[:page])
    respond_to do |format|
      format.html { render 'explore'}
      format.json {render json: @posts}
    end
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html {}
      format.json {render json: @post}
    end
  end

  def edit
    respond_to do |format|
      format.html {}
      format.json {render json: @post}
    end
  end

  def create
    @post = current_user.posts.build(post_params)
    
    respond_to do |format|
      if @post.save
        format.html {redirect_to posts_user_path(current_user), notice: "Post sucessfully created."}
        format.json {render json: @post}
      else
        get_topics
        format.html {render 'new'}
        format.json {render json:{}, status: :unprocessable_enity}
      end
    end
  end

  def update
    @post.update(post_params)
    respond_to do |format|
      if @post.update(post_params)
        format.html {redirect_to posts_user_path(current_user), notice: "Post sucessfully updated."}
        format.json {render json: @post}
      else
        get_topics
        format.html {render 'edit'}
        format.json {render json:{}, status: :unprocessable_enity}
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html {redirect_to posts_path, notice: "Post sucessfully destroyed."}
      format.json {render json: {}}
    end
  end

  private
    def set_post
      if params[:id].match(/^[0-9]+$/)
        post = Post.find_by(id: params[:id])
        redirect_to(seo_post_path(post.user, post), :status => :moved_permanently) if post
      end

      @post = Post.published.friendly.find(params[:id])
      not_found unless @post
    end

    def set_user_post
      @post = current_user.posts.friendly.find(params[:id])
      not_found unless @post
    end

    def post_params
      params.require(:post).permit(:content, :title, :subtitle, :user_id, :published, topic_ids: [], tags: [])
    end

    def full_profile_user
      # redirect_to edit_user_registration_path, notice: 'Please tell us more about you before you add a post.' if current_user.short_profile
    end

    def get_topics
      @topics = Topic.all.order('title')
    end

    def parse_tags
      params[:post][:tags] = params[:post][:tags].split(",").map(&:strip).compact if params[:post][:tags].present?
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>

    <ul class='alert alert-warning list-unstyled'>
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved</h2>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  <% end %>
  <div class='form-group'>
    <%= f.text_field :title, class: 'form-control input-lg', placeholder: 'Title' %>
  </div>
  <div class='form-group'>
    <%= f.text_field :subtitle, class: 'form-control input-lg', placeholder: 'Subtitle' %>
  </div>

  <div class='form-group'>
    <%= f.collection_select :topic_ids, @topics, :id, :title, {},  {:multiple => true, class: 'form-control'} %>
    <i class='help-block'>
      (You can select from multiple topics)
    </i>
  </div>

  <div class='form-group'>
    <div>
      <%= f.text_area :content, rows: 20 %>
    </div>
    <%= link_to 'Keyboard shortcuts','http://imperavi.com/redactor/docs/shortcuts/', class: 'blue', target: '_blank' %>
  </div>

  <div class='form-group'>
    <%= f.label :tags, 'Tags(separated by comma)' %>
    <%= f.text_field :tags, class: 'form-control', value: @post.tags.join(", ") %>
  </div>

  <div class="actions">
    <%= f.submit 'Publish', class: 'btn btn-success' %>
    <% if @post.new_record? || !@post.published %>
      <%= f.hidden_field :published, value: true  %>
      <%= link_to 'Save Draft', '#sd' , class: 'btn btn-warning', id: 'js-save-draft' %>
    <% end %>
  </div>
<% end %>

app/views/posts/_pmenu.html.erb
<div class="nav text-center">
  <a href="<%= posts_path %>" data-target='.home-page-posts' class="<%= 'active' if action_name == 'index' && controller_name == 'posts' %>">Posts</a>
  <a href="<%= explore_posts_path %>" data-target='.home-page-explore' class="<%= 'active' if action_name == 'explore' || action_name == 'search' %>">Explore</a>
  <% if user_signed_in? %>
    <a href="<%= feed_posts_path %>" data-target='.home-page-posts' class="<%= 'active' if action_name == 'feed' %>">Feed</a>
  <% end %>
  <a href="<%= topics_posts_path %>" data-target='.home-page-categories' class="<%= 'active' if action_name == 'topics' %>">Topics</a>
  <a href="<%= users_path %>" data-target='.home-page-categories' class="<%= 'active' if (action_name == 'index' || 'pindex') && controller_name == 'users' %>">People</a>
</div>

app/views/posts/_post.html.erb
<div class="post">
  <section>
    <div class="post-preview col-xs-10  no-gutter">

      <h2>
        <%= link_to post.title, seo_post_path(post.user, post) %>
        
      </h2>
      <p><%= post.subtitle %></p>
      <% if current_user.try(:id) == post.user.id %>
        <ul class='list-inline'>
          <li>
            <%= link_to 'Edit <i class="entypo-pencil"></i>'.html_safe, edit_post_path(post), title: 'Edit Post', class: 'label label-danger' %>
          </li>
          <% if !post.published %>
            <li>
              <%= link_to 'Publish <i class="entypo-publish"></i>'.html_safe, publish_post_path(post), title: 'Publish Post', class: 'label label-success publish-post-link', remote: true, method: 'post', data: {type: 'json', disable_with: 'Wait..'} %>
            </li>
          <% end %>
        </ul>
      <% end %>
      <p class="meta">
        <%= link_to post.user.username, post.user %> in
        <% topic_links = post.topics.map do |topic| %>
          <% link_to topic.title, topic_path(topic) %>
        <% end %> 
        <%= topic_links.to_sentence.html_safe %><i class="link-spacer"></i> <i class="entypo-bookmark"></i> <%= post.duration %> minute read<i class="link-spacer"></i> <i class="entypo-heart"></i><%= pluralize(post.likes_count, 'like')  %> it
      </p>
    </div>

    <div class=" col-xs-2  no-gutter">
  
      <%= image_tag post.user.avatar.thumb, class: 'user-icon user-1', alt: post.user.name %>
 
    </div>

  </section>
</div>

app/views/posts/_top_posts.html.erb
<% if top_posts.present? %>
<div class="row">
  <div class="top-posts col-xs-12">
    <h2><i class="entypo-trophy"></i><%= top_posts.length %> Top Posts</h2>
  </div>
    
  <% top_posts.each do |top_post| %>
    <div class="col-xs-12 col-sm-3 col-md-2">
      <span class="view-count"><%= top_post.likes_count %></span>
    </div>
    <div class="col-xs-12 col-sm-9 col-md-10">
      <h3 class="top-post"><%= link_to top_post.title, seo_post_path(top_post.user, top_post) %></h3>
    </div>
  <% end %>

</div>
<% end %>

app/views/posts/_topics.html.erb
<div class="home-page-categories animated fadeIn ">
  <h1 class='text-center'>Topics</h1>
  <hr>
  <div class="category row row-centered">
    <section>
      <% topics.each do |topic| %>
        <div class="category-preview col-centered col-xs-12 col-sm-4">
          <%= follow_or_unfollow(topic, '', @following_ids) %>
          <h2 class='alpha'>
            <%= topic.title %>
          </h2>

          <%= link_to topic_path(topic) do %>
            <%= image_tag topic.splash.medium.url, alt: 'category-image' %>
          <% end %>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/posts/edit.html.erb
<%
  title "Edit #{@post.title}"
%>
<h2 class='text-center'><%= @post.title %></h2>
<hr>
<%= render 'form' %>

app/views/posts/explore.html.erb
<%
  title t('.meta_title')
  description t('.meta_description')
  
%>

<%= render partial: 'pmenu' %>

<div class="home-page-posts animated fadeIn ">
  <%= render partial: 'shared/big_search' %>

  <% if @posts.present? %>
  <div class="animated fadeIn">
    <%= render @posts %>  
    <%= paginate @posts %>
  </div><!-- Home page posts -->
<% end %>
</div>

app/views/posts/feed.html.erb
<%
  title t('.meta_title')
  description t('.meta_description')
  
%>
<%= render partial: 'pmenu' %>

<div class="home-page-posts animated fadeIn">
  <h1 class='text-center'>Posts from Topics You Follow</h1>
  <hr>
  <%= render @posts %>  
  <%= paginate @posts %>
</div>

app/views/posts/index.html.erb
<%
  title t('.meta_title')
  description t('.meta_description')
  
%>

<% unless action_name == 'top' %>
  <% canonical posts_url %>
<% else %>
  <% canonical top_posts_url %>
<% end %>

<%= render partial: 'pmenu' %>

<div class="home-page-posts animated fadeIn">
  <% unless action_name == 'top' %>
    <h1 class='text-center'>Recent Post</h1>
  <% else %>
    <h1 class='text-center'>Top Post</h1>
  <% end %>
  <hr>
  <% unless action_name == 'top' %>
    <div class="nav text-right m-t-15">
      <%= link_to 'Top Posts', top_posts_path, class: 'pull-right' %>
    </div>
  <% end %>

  <%= render @posts %>
  <%= paginate @posts %>
</div><!-- Home page posts -->

app/views/posts/new.html.erb
<%
  title 'Add new post'
%>
<h2 class='text-center'>Add New Post</h2>
<hr>
<%= render 'form' %>

app/views/posts/show.html.erb
<%
  title t('.meta_title', title: @post.seo_title)
  description t('.meta_description', description: @post.seo_description)
  keywords @post.seo_tags
  canonical seo_post_url(@post.user, @post)
%>
<% content_for :js do %>
  <script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "NewsArticle",
      "headline": "<%= @post.title %>",
      "datePublished": "<%= @post.updated_at.iso8601 %>",
      "description": "<%= @post.subtitle %>",
      "articleBody": "<%= @post.content %>"
    }
  </script>
  <script type="text/javascript">
    setTimeout(function(){
      $.post('<%= rcount_post_path(@post) %>',{ inc: 'yes'}, function(data, textStatus, xhr) {
        /*optional stuff to do after success */
      });
    }, 55000);
  </script>
<% end %>
<%= render partial: 'users/profile', locals: {user: @post.user} %>
<h1 class='text-center'>
  <%= @post.title %>
</h1>
<% if @post.subtitle.present? %>
<h2 class='text-center text-muted'>
  <%= @post.subtitle %>
</h2>
<hr class='m-t-b-30'>
<% end %>
<div class='post-content'>
  <%= @post.content.html_safe %>
</div>
<div class="single-footer">
  <div class="social clearfix">
    <% unless current_user %>
      <%= link_to '<i class="entypo-heart"></i>Like'.html_safe, user_session_path(alert: 'like') , class: 'btn btn-writer btn-like login' %>
    <% else %>
      <% if current_user.like?(@post) %>
        <%= link_to user_path(current_user) do %>
          <%= image_tag current_user.avatar.thumb.url, class: 'liked-this-icon', alt: current_user.name %>
        <% end %>
      <% else %>
        <%= link_to '<i class="entypo-heart"></i>Like'.html_safe, like_post_path(@post) , class: 'btn btn-writer btn-like', data: {disabled_with: 'Wait..', type: 'json' }, remote: true, method: 'post', id: 'like-post'  %>
      <% end %>
    <% end %>
    <% @likes.each do |like| %>
      <% next if like.user_id == current_user.try(:id) %>
      <%= link_to user_path(like.user) do %>
        <%= image_tag like.user.avatar.thumb.url, class: 'liked-this-icon', alt: like.user.name %>
      <% end %>
    <% end %>


      <a class="social-icon" href="<%= tweet_referral_link_url(@post) %>", target= '_blank'>
          <i class="entypo-twitter"></i>
      </a>
      <a class="social-icon" target="_blank" href="<%= facebook_referral_link_url(@post) %>">
          <i class="entypo-facebook-squared"></i>
      </a>

      

  </div>
  <div class="m-t-b-30">
    <%= subscribe_or_not(@user) if @user != current_user%>
  </div>
  <div class="category-list">
      <p>Also found in</p>
      <ul>
        <% @post.topics.each do |topic| %>
          <li>
            <%= link_to topic.title, topic_path(topic) %>
          </li>
        <% end %>
          
      </ul>
  </div>
  <div class="category-list">
      <p>Tags</p>
      <ul>
        <% @post.tags.each do |tag| %>
          <li>
            <%= link_to tag, tag_path(id: tag) %>
          </li>
        <% end %>
      </ul>
  </div>
</div>
<% if Rails.env.production? %>
<%= render partial: 'shared/discuss', locals: {post: @post} %>
<% end %>

app/views/posts/topics.html.erb
<%
  title t('.meta_title')
  description t('.meta_description')
  keywords @topics[0..10].map(&:title)
  canonical topics_posts_url
%>
<%= render partial: 'pmenu' %>
<%= render partial:  'topics', locals: {topics: @topics} %>