config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  

  root 'home#index'

  get '/about' => 'home#about', as: :about
  get '/privacy' => 'home#privacy', as: :privacy
  get '/tos' => 'home#tos', as: :tos
  get '/:profession_id/u' => 'users#pindex', as: :profession_users
  get '/:user_id/projects/:id' => 'projects#show', as: :user_project

  resources :projects, only: [:create, :edit, :new, :update, :destroy]

  resources :users, only: [:index, :show] , path: 'u' do
    member do
      get 'dashboard'
      get 'likes'
      get 'posts'
      get 'hireme'
      post 'hireme'
      get 'drafts'
      post 'subscribe'
      post 'unsubscribe'
    end
  end

  resources :tags, only: [:show], path: 'tag' do
  end

  
  resources :posts, only: [:create, :edit, :update, :destroy, :new, :index] do
    collection do
      post :autosave
      get 'search'
      get 'explore'
      get 'topics'
      get 'feed'
      get 'top'
    end
    
    member do
      post 'publish'
      post 'like'
      post 'rcount' => 'posts#increment_read_count'
    end
  end
  resources :topics, only: [:show, :update, :new, :edit, :create], path: 't'
  get '/search' => 'posts#search', as: 'search'
  get ':user_id/:id' => 'posts#show', as: 'seo_post'

  resources :likes, only: [:index, :update, :destroy, :create]

  resources :post_assets, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="home-footer text-center">
  <%= link_to 'About', about_path %>
  <i class="link-spacer"></i>
  <%= link_to 'Privacy', privacy_path %>
  <i class="link-spacer"></i>
  <%= link_to 'Terms of Service', tos_path %>
  <i class="link-spacer"></i>
  <%= mail_to "Contact", 'sayhi@weareindiatech.com' %>
  <i class="link-spacer"></i>
  <a href="post.html"> ©2014 WeAreIndiatech. All rights reserved. </a>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'shared/favicons' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= display_meta_tags %>
  <%= javascript_include_tag 'theme/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--[if lt IE 10]>
    <%= javascript_include_tag 'jquery.placeholder' %>
    <%= javascript_include_tag 'ie9' %>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/bar' %>
  <% if controller_name == 'home' %>
    <%= render 'shared/home_splash' %>
  <% else %>
    <%= render 'shared/noscript_menu' %>
  <% end %>
  <div class="container">
    <div class="row">
      <div id='menu'>
        <%= render 'shared/menu_items' %>
      </div>
      <div class="col-sm-12 main-content single-content">
        <%= render partial: 'shared/flash', locals: { flash: flash } %>
        <%= yield %>
        <%= render partial:   'layouts/footer' %>
      </div><!-- main content -->
    </div> <!--/row -->
  </div> <!-- /container -->
<%= yield :js %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65670286-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/sidebar.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <%= display_meta_tags %>
  <%= javascript_include_tag 'theme/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container home-container">
    <div class="row">
      <% if @topic %>
        <%= render 'shared/sidebar_topic' %>
      <% else %>
        <%= render 'shared/sidebar' %>
      <% end %>
      <div class="col-md-7 col-sm-12 col-md-offset-5 main-content">
        <%= render partial: 'shared/flash', locals: { flash: flash } %>
        <%= yield %>
      </div><!-- main content -->
    </div> <!--/row -->
  </div> <!-- /container -->

</body>
</html>